// ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//
// PaletteExport.swift
//
//
// Created by Steven Marcotte on 2026-Aug-27
// Copyright (c) 1996 - 2026 Steven Marcotte, All Rights Reserved
//
// ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Foundation


// MARK: -
// ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

enum ExportFormat: String, CaseIterable, Identifiable {

    case swift = "Color+Palette.swift"
    case assets = "Assets.xcassets"
    case tokens = "Tokens.json"

    var id: String { rawValue }
    var label: String { rawValue }

    var fileExtension: String {
        switch self {
            case .swift:  "swift"
            case .assets: "json"
            case .tokens: "json"
        }
    }
}


// MARK: -
// ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

enum PaletteExport {

    static func code(for palette: Palette, format: ExportFormat, lattice: MantiaLattice) -> String {
        switch format {
            case .swift:  swiftSource(palette)
            case .assets: assetCatalog(palette)
            case .tokens: tokensJSON(palette, lattice: lattice)
        }
    }


    // MARK: - Color extension
    // ————————————————————————————————————————————————————————————————————————————————————————————————————————————————

    private static func swiftSource(_ palette: Palette) -> String {
        let enumName = palette.name.filter { $0.isLetter || $0.isNumber }
        let body = palette.orderedSwatches.map { swatch -> String in
            let c = swatch.hsb.rgb
            let roleComment = swatch.role.map { "  ·  \($0.rawValue)%" } ?? ""
            return """
                        /// \(swatch.hsb.hexDisplay)\(roleComment)
                        static let \(identifier(swatch.name)) = Color(
                            .sRGB, red: \(f3(c.red)), green: \(f3(c.green)), blue: \(f3(c.blue)), opacity: 1
                        )
                    """
        }.joined(separator: "\n")

        return """
            import SwiftUI

            // Generated by PaletteMonkey — \(palette.name)
            extension Color {
                enum \(enumName.isEmpty ? "Palette" : enumName) {
            \(body)
                }
            }

            """
    }


    // MARK: - Asset catalog
    // ————————————————————————————————————————————————————————————————————————————————————————————————————————————————

    private static func assetCatalog(_ palette: Palette) -> String {
        guard let swatch = palette.orderedSwatches.first else {
            return "// \(palette.name) has no swatches to export.\n"
        }

        let light = swatch.hsb
        let dark  = DarkVariant.of(light, role: swatch.role)

        return """
            // \(palette.name)/\(swatch.name).colorset/Contents.json
            {
              "colors": [
                { "idiom": "universal",
                  "color": { "color-space": "srgb", "components": \(components(light)) } },
                { "idiom": "universal",
                  "appearances": [{ "appearance": "luminosity", "value": "dark" }],
                  "color": { "color-space": "srgb", "components": \(components(dark)) } }
              ],
              "info": { "author": "palettemonkey", "version": 1 }
            }

            // One .colorset per swatch — \(palette.orderedSwatches.count) written on export.

            """
    }

    private static func components(_ value: HSB) -> String {
        let c = value.rgb255
        func byte(_ v: Int) -> String { "0x" + String(format: "%02X", v) }
        return #"{ "red": "\#(byte(c.red))", "green": "\#(byte(c.green))", "blue": "\#(byte(c.blue))", "alpha": "1.000" }"#
    }


    // MARK: - Tokens
    // ————————————————————————————————————————————————————————————————————————————————————————————————————————————————

    /// Hand-built rather than encoded, so key order stays stable and the file
    /// diffs cleanly between exports.
    private static func tokensJSON(_ palette: Palette, lattice: MantiaLattice) -> String {

        let colors = palette.orderedSwatches.map { swatch -> String in
            let hsb = swatch.hsb
            let ok = hsb.oklch
            let tags = swatch.tags.map { "\"\($0)\"" }.joined(separator: ", ")

            return """
                    {
                      "name": \(quote(swatch.name)),
                      "hex": "\(hsb.hexDisplay)",
                      "role": \(swatch.role.map { "\"\($0.rawValue)\"" } ?? "null"),
                      "tags": [\(tags)],
                      "hsb": [\(Int(hsb.hue.rounded())), \(Int((hsb.saturation * 100).rounded())), \(Int((hsb.brightness * 100).rounded()))],
                      "oklch": [\(f2(ok.l)), \(f4(ok.c)), \(Int(ok.h.rounded()))],
                      "onMantiaStop": \(lattice.isOnStop(hsb) ? "true" : "false"),
                      "source": \(quote(swatch.source.label)),
                      "note": \(swatch.note.isEmpty ? "null" : quote(swatch.note))
                    }
                """
        }.joined(separator: ",\n")

        return """
            {
              "palette": \(quote(palette.name)),
              "hueStep": \(trimmed(lattice.hueStep)),
              "sbSteps": \(lattice.steps),
              "colors": [
            \(colors)
              ]
            }

            """
    }


    // MARK: - Formatting
    // ————————————————————————————————————————————————————————————————————————————————————————————————————————————————

    /// Lower-camel-cases a display name into a usable Swift identifier.
    static func identifier(_ name: String) -> String {
        let words = name
            .map { $0.isLetter || $0.isNumber ? $0 : " " }
            .reduce(into: "") { $0.append($1) }
            .split(separator: " ")

        guard !words.isEmpty else { return "color" }

        let head = words[0].lowercased()
        let tail = words.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }
        let joined = ([head] + tail).joined()

        // An identifier cannot lead with a digit.
        return joined.first?.isNumber == true ? "color\(joined)" : joined
    }

    private static func f2(_ v: Double) -> String { String(format: "%.2f", v) }
    private static func f3(_ v: Double) -> String { String(format: "%.3f", v) }
    private static func f4(_ v: Double) -> String { String(format: "%.4f", v) }

    private static func trimmed(_ v: Double) -> String {
        v == v.rounded() ? String(Int(v)) : String(v)
    }

    private static func quote(_ s: String) -> String {
        var out = ""
        for ch in s.unicodeScalars {
            switch ch {
                case "\"": out += "\\\""
                case "\\": out += "\\\\"
                case "\n": out += "\\n"
                case "\t": out += "\\t"
                default:   out.unicodeScalars.append(ch)
            }
        }
        return "\"\(out)\""
    }
}
